// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cvr-chart-variants/VariantA.tsx": () => import("../components/mockups/cvr-chart-variants/VariantA.tsx"),
  "./components/mockups/cvr-chart-variants/VariantB.tsx": () => import("../components/mockups/cvr-chart-variants/VariantB.tsx"),
  "./components/mockups/cvr-chart-variants/VariantC.tsx": () => import("../components/mockups/cvr-chart-variants/VariantC.tsx"),
  "./components/mockups/cvr-chart-variants/VariantD.tsx": () => import("../components/mockups/cvr-chart-variants/VariantD.tsx"),
  "./components/mockups/dashboard-designs/DesignA.tsx": () => import("../components/mockups/dashboard-designs/DesignA.tsx"),
  "./components/mockups/dashboard-designs/DesignB.tsx": () => import("../components/mockups/dashboard-designs/DesignB.tsx"),
  "./components/mockups/dashboard-designs/DesignC.tsx": () => import("../components/mockups/dashboard-designs/DesignC.tsx"),
  "./components/mockups/newsletter-ui-proposals/ABPanel.tsx": () => import("../components/mockups/newsletter-ui-proposals/ABPanel.tsx"),
  "./components/mockups/newsletter-ui-proposals/CardSelector.tsx": () => import("../components/mockups/newsletter-ui-proposals/CardSelector.tsx"),
  "./components/mockups/newsletter-ui-proposals/PresetBar.tsx": () => import("../components/mockups/newsletter-ui-proposals/PresetBar.tsx"),
  "./components/mockups/segment-compare/CardSelector.tsx": () => import("../components/mockups/segment-compare/CardSelector.tsx"),
  "./components/mockups/segment-compare/FilterBar.tsx": () => import("../components/mockups/segment-compare/FilterBar.tsx"),
  "./components/mockups/segment-compare/PanelView.tsx": () => import("../components/mockups/segment-compare/PanelView.tsx")
};
